/**
 * ExportDialog Component
 * Provides export functionality for dashboard data:
 * - CSV export of filtered articles
 * - PDF report generation (placeholder)
 * - Share link with current filters
 * - Email summary template
 */

import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Download,
  FileText,
  Mail,
  Link as LinkIcon,
  Check,
} from "lucide-react";
import type { ArticleSummary, KPI } from "@/types/dashboard";
import { toast } from "sonner";

interface ExportDialogProps {
  articles: ArticleSummary[];
  kpis: KPI[];
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

type ExportFormat = "csv" | "pdf" | "link" | "email";

export function ExportDialog({
  articles,
  kpis,
  open,
  onOpenChange,
}: ExportDialogProps) {
  const [exportFormat, setExportFormat] = useState<ExportFormat>("csv");
  const [includeFullText, setIncludeFullText] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleExport = () => {
    switch (exportFormat) {
      case "csv":
        exportToCSV();
        break;
      case "pdf":
        exportToPDF();
        break;
      case "link":
        copyShareLink();
        break;
      case "email":
        generateEmailTemplate();
        break;
    }
  };

  const exportToCSV = () => {
    // Prepare CSV data
    const headers = [
      "Title",
      "Source",
      "Category",
      "Date",
      "Sentiment",
      "Sentiment Score",
      "Summary",
      ...(includeFullText ? ["Full Text"] : []),
      "URL",
      "Author",
      "Credibility Score",
    ];

    const rows = articles.map((article) => [
      article.title,
      article.source,
      article.category,
      new Date(article.publishedAt).toLocaleDateString(),
      article.sentiment,
      article.sentimentScore.toFixed(2),
      article.summary,
      ...(includeFullText ? [article.fullText || ""] : []),
      article.url,
      article.author || "",
      article.credibilityScore?.toString() || "",
    ]);

    // Convert to CSV string
    const csvContent = [
      headers.join(","),
      ...rows.map((row) =>
        row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(",")
      ),
    ].join("\n");

    // Download file
    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const link = document.createElement("a");
    const url = URL.createObjectURL(blob);
    link.setAttribute("href", url);
    link.setAttribute(
      "download",
      `pm-office-articles-${new Date().toISOString().split("T")[0]}.csv`
    );
    link.style.visibility = "hidden";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    toast.success("CSV exported successfully", {
      description: `${articles.length} articles exported`,
    });
    onOpenChange(false);
  };

  const exportToPDF = () => {
    // Placeholder for PDF generation
    // In production, you would use a library like jsPDF or pdfmake
    toast.info("PDF export coming soon", {
      description: "This feature will generate an executive summary PDF",
    });
    onOpenChange(false);
  };

  const copyShareLink = () => {
    // Get current URL with filters (in production, you'd encode filter state)
    const shareUrl = window.location.href;

    navigator.clipboard.writeText(shareUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);

    toast.success("Link copied to clipboard", {
      description: "Share this link to preserve current filters",
    });
  };

  const generateEmailTemplate = () => {
    // Generate markdown email summary
    const summary = `# PM Office Intelligence Dashboard - Daily Brief

## Summary Statistics
- Total Articles: ${articles.length}
- Active KPIs: ${kpis.length}
- Date: ${new Date().toLocaleDateString()}

## KPI Overview
${kpis
  .slice(0, 5)
  .map(
    (kpi) =>
      `- **${kpi.name}**: ${kpi.currentScore.toFixed(1)} (${
        kpi.trend === "up" ? "↑" : kpi.trend === "down" ? "↓" : "→"
      } ${kpi.articleCount} articles)`
  )
  .join("\n")}

## Top Articles
${articles
  .slice(0, 5)
  .map(
    (article) =>
      `### ${article.title}
- **Source**: ${article.source}
- **Sentiment**: ${article.sentiment}
- **Summary**: ${article.summary.substring(0, 200)}...
- **Read more**: ${article.url}
`
  )
  .join("\n")}

---
Generated by PM Office Intelligence Dashboard
`;

    // Copy to clipboard
    navigator.clipboard.writeText(summary);

    toast.success("Email template copied", {
      description: "Paste into your email client",
    });
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Export Data</DialogTitle>
          <DialogDescription>
            Export {articles.length} filtered articles in your preferred format
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6 py-4">
          {/* Format Selection */}
          <RadioGroup value={exportFormat} onValueChange={(v: ExportFormat) => setExportFormat(v)}>
            <div className="flex items-center space-x-3 p-3 border rounded-lg hover:bg-muted/50 cursor-pointer">
              <RadioGroupItem value="csv" id="csv" />
              <Label htmlFor="csv" className="flex-1 cursor-pointer">
                <div className="flex items-center gap-3">
                  <FileText className="h-5 w-5 text-primary" />
                  <div>
                    <p className="font-medium">CSV Spreadsheet</p>
                    <p className="text-xs text-muted-foreground">
                      Export articles as comma-separated values
                    </p>
                  </div>
                </div>
              </Label>
            </div>

            <div className="flex items-center space-x-3 p-3 border rounded-lg hover:bg-muted/50 cursor-pointer">
              <RadioGroupItem value="pdf" id="pdf" />
              <Label htmlFor="pdf" className="flex-1 cursor-pointer">
                <div className="flex items-center gap-3">
                  <Download className="h-5 w-5 text-primary" />
                  <div>
                    <p className="font-medium">PDF Report</p>
                    <p className="text-xs text-muted-foreground">
                      Generate executive summary with charts
                    </p>
                  </div>
                </div>
              </Label>
            </div>

            <div className="flex items-center space-x-3 p-3 border rounded-lg hover:bg-muted/50 cursor-pointer">
              <RadioGroupItem value="link" id="link" />
              <Label htmlFor="link" className="flex-1 cursor-pointer">
                <div className="flex items-center gap-3">
                  <LinkIcon className="h-5 w-5 text-primary" />
                  <div>
                    <p className="font-medium">Share Link</p>
                    <p className="text-xs text-muted-foreground">
                      Copy link with current filters applied
                    </p>
                  </div>
                </div>
              </Label>
            </div>

            <div className="flex items-center space-x-3 p-3 border rounded-lg hover:bg-muted/50 cursor-pointer">
              <RadioGroupItem value="email" id="email" />
              <Label htmlFor="email" className="flex-1 cursor-pointer">
                <div className="flex items-center gap-3">
                  <Mail className="h-5 w-5 text-primary" />
                  <div>
                    <p className="font-medium">Email Template</p>
                    <p className="text-xs text-muted-foreground">
                      Generate markdown summary for email
                    </p>
                  </div>
                </div>
              </Label>
            </div>
          </RadioGroup>

          {/* Options */}
          {exportFormat === "csv" && (
            <div className="space-y-3 pt-2">
              <Label className="text-sm font-medium">Export Options</Label>
              <div className="flex items-center space-x-2">
                <Checkbox
                  id="fulltext"
                  checked={includeFullText}
                  onCheckedChange={(checked) => setIncludeFullText(checked === true)}
                />
                <Label
                  htmlFor="fulltext"
                  className="text-sm font-normal cursor-pointer"
                >
                  Include full article text (larger file size)
                </Label>
              </div>
            </div>
          )}
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button onClick={handleExport}>
            {copied ? (
              <>
                <Check className="h-4 w-4 mr-2" />
                Copied!
              </>
            ) : (
              <>
                <Download className="h-4 w-4 mr-2" />
                Export
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
